# Generated by Django 4.2.13 on 2024-05-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbookrating", name="RD", field=models.FloatField(default=30),
        ),
        migrations.AddField(
            model_name="userbookrating",
            name="elo_rating",
            field=models.FloatField(default=1400),
        ),
    ]
