# Generated by Django 5.0.6 on 2024-12-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='RD',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='bucket',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='date_finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='elo_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='is_ranked',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
