# Generated by Django 5.0.6 on 2024-12-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='childrens_ranked_books_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='fiction_ranked_books_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='nonfiction_ranked_books_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
