# Generated by Django 4.2.13 on 2024-06-07 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapp", "0002_userbookrating_rd_userbookrating_elo_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbookrating",
            name="RD",
            field=models.FloatField(default=400),
        ),
        migrations.AlterField(
            model_name="userbookrating",
            name="elo_rating",
            field=models.FloatField(default=1500),
        ),
        migrations.CreateModel(
            name="UserToBeRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_id", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("user", "work_id")},},
        ),
    ]
