# Generated by Django 5.0.6 on 2024-12-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_useraccount_childrens_ranked_books_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='total_ranked_books_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
