# Generated by Django 4.2.13 on 2024-06-08 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapp", "0003_alter_userbookrating_rd_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_id", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image_url", models.URLField()),
                ("viewed", models.BooleanField(default=False)),
                ("reference_work_id", models.CharField(max_length=50)),
                ("score", models.FloatField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("user", "work_id")},},
        ),
    ]
