# Generated by Django 4.2.13 on 2024-06-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapp", "0004_userrecommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrecommendation",
            name="outcome",
            field=models.BooleanField(null=True),
        ),
    ]
