# Generated by Django 5.0.6 on 2024-06-16 00:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_userrecommendation_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookrating',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
