# Generated by Django 5.0.6 on 2024-06-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_userbookrating_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookrating',
            name='ranked',
            field=models.BooleanField(default=False),
        ),
    ]
