# Generated by Django 5.0.6 on 2024-06-16 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_userbookrating_ranked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbookrating',
            old_name='ranked',
            new_name='is_ranked',
        ),
    ]
