# Generated by Django 5.0.6 on 2024-06-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0008_rename_ranked_userbookrating_is_ranked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrating',
            name='rating',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10, null=True),
        ),
    ]
