# Generated by Django 5.0.6 on 2024-06-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_alter_userbookrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookrating',
            name='description',
            field=models.TextField(default='Sample description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbookrating',
            name='image_url',
            field=models.URLField(default='https://images.gr-assets.com/books/1394988109m/22034.jpg'),
            preserve_default=False,
        ),
    ]
