# Generated by Django 5.0.6 on 2024-08-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0010_userbookrating_description_userbookrating_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoberead',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
