# Generated by Django 5.0.6 on 2024-08-03 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0011_usertoberead_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoberead',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
