# Generated by Django 5.0.6 on 2024-12-02 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0012_usertoberead_date_added'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserToBeRead',
            new_name='TBRBook',
        ),
        migrations.RenameModel(
            old_name='UserBookRating',
            new_name='UserBook',
        ),
    ]
